version: '3.8'

services:
  
  ui:
    image: ninepiece2/bo6-terminus-equation-calculator:latest
    container_name: BO6-Terminus-Equation-Calculator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: BO6-Terminus-Equation-Calculator-Nginx-Proxy
    restart: always
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/nginx/ssl:ro
    depends_on:
      - ui